# Generated by Django 5.2.4 on 2025-10-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messgaes",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("bot", "Bot")],
                default="user",
                max_length=10,
            ),
        ),
    ]
