# Generated by Django 5.2.4 on 2025-10-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Chats", "0002_messgaes_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messgaes",
            old_name="message",
            new_name="content",
        ),
    ]
