# Generated by Django 5.2.4 on 2025-10-14 18:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Chats", "0003_rename_message_messgaes_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Messgaes",
            new_name="Messages",
        ),
    ]
